# Generated by Django 5.1.3 on 2024-11-26 04:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='course',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
