# Generated by Django 5.1.3 on 2024-11-26 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_form_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='choices',
        ),
        migrations.AddField(
            model_name='choices',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='faculty.questions'),
            preserve_default=False,
        ),
    ]
