# Generated by Django 5.1.3 on 2024-11-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_remove_questions_choices_choices_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexaminfo',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
