# Generated by Django 5.1.3 on 2024-12-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0009_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='hrs',
            field=models.FloatField(default=1),
        ),
    ]
