# Generated by Django 5.1.3 on 2024-12-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0010_form_hrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexaminfo',
            name='attempted',
            field=models.BooleanField(default=False),
        ),
    ]
