# Generated by Django 5.1.3 on 2024-12-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0011_studentexaminfo_attempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
