# Generated by Django 5.1.3 on 2024-12-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0012_responses_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexaminfo',
            name='total_score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
